decimal: 5
print_in_compiler: false
print_total_table: false
create_reports: false
create_highlight_reports: false
one_file_report: ""
project_name: "test_project"
package_1: "folder1"
package_2: "folder2"
base_directory: "C:/Users/15717/Desktop/projects"

paths:
  project_path: "{base_directory}/{project_name}"
  package1_directory: "{base_directory}/{project_name}/{package_1}"
  package2_directory: "{base_directory}/{project_name}/{package_2}"
  package_report_name: "REPORT_{project_name}"
  package_report_path: "{base_directory}/{project_name}/REPORT_{project_name}"