services:
  - type: web
    name: file-comparator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    runtime: python
    region: oregon
    branch: main
    autoDeploy: true
